name: Workflow C

on:
  push:
    branches: ["main"]

jobs:
  some_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Some Step
        run: echo "Bonjour le monde !"
      - name: reuse steps
        uses: ./.github/actions/D.yml
